### ISSUE TITLE
Installation: conda vs pip

### ISSUE THREAD

**Issue by steko** [alan-turing-institute/Palaeoanalytics#130]
Hi, the installation instructions for conda work without any problem but I was curious to understand the need for a separate step with pip.
While doing this, I found out that the installation of all dependencies, including OpenCV, work well even if done entirely with pip in a virtual environment:

```
pip install opencv-contrib-python
pip install .
```

The above commands worked well for me on Linux (i.e. I was able to run the script with the example data and obtain the correct results. Just installing `opencv` resulted in some errors about angle measurements. Of course if `opencv-contrib-python` is added to the requirements there is no need for a separate install step - at least with pip.

What do you think about adding this to the README install instructions?

**Comment by steko** [comment]
I tested the same pip-based procedure on Windows. I can confirm it works well.

**Comment by steko** [comment]
Mentioning https://github.com/openjournals/joss-reviews/issues/3738

**Comment by crangelsmith** [comment]
Hi @steko, thank you for your comment! The reason for this mix is that we had some issues with the opencv installation with pip (it would take hours to build, I think due to my OS). However, I think that problem is fixed now so I'll move all the installation instructions to pip only, it definitely makes more sense this way.

This is implemented in PR #132 that will be first merged to `develop` and once all reviews from JOSS are finished we'll merge to `main`.

**Comment by JasonGellis** [comment]
@steko We have addressed this issue in PR #133  and have merged into the main branch. We will now close this issue.

**Comment by steko** [comment]
@JasonGellis the README and the Travis configuration file still have a mix of pip and conda. Everything works, but I think it makes the installation process more fragile.

**Comment by JasonGellis** [comment]
@steko please see the updated installation instructions on this branch: joss_paper/139_native_install
https://github.com/alan-turing-institute/Palaeoanalytics/tree/joss_paper/139_native_install

Once this is aproved by JOSS, I will merge into the main branch.

**Comment by JasonGellis** [comment]
@steko This issue has been corrected and merged into the main branch.
